### ISSUE TITLE
Pipeline tensorflow installation, conda or other way.

### ISSUE THREAD

**Issue by matscorse** [icenet-ai/icenet-pipeline#32]
There is a note in icenet installation:

> Bear in mind when installing icenet (and by dependency tensorflow) you will need to be on a CUDA/GPU enabled machine for binary 
> linkage. As per current (end of 2022) tensorflow guidance do not install it via conda.

So when performing " pip install -e . " I assume this isn't using conda but is using pip. If I run this on a non gpu workstation is my install broken?

**Comment by JimCircadian** [comment]
Hi @matscorse: if you run `pip` within a conda environment, that's fine. It means that you'll be leveraging the python install within that conda environment. In the conda environment created by `icenet-pipeline`, and on the BAS HPC specifically, the GPU libraries are all available so you don't need to worry too much about linking to cuda etc, it'll happen based on the requirements specified in the python project. 

If you continue through the instructions you should see that the whole thing works with a GPU when you get to the training step. If it doesn't we can reinstall tensorflow on a GPU enabled machine and make sure, but that probably won't be the case. Either way, assume your environment is fine until something suggest otherwise! :) 

Hope that helps!

**Comment by bnubald** [comment]
Closing as solved, please do feel free reopen if you needed more clarification @matscorse!
